language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "sooglejay"
  - git config user.email "394055524@qq.com"
  - git add -A
  - git commit -m "Update From Travis"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
 global:
   - GH_REF: github.com/sooglejay/sooglejay.github.io.git

branches:
  only:
    - dev
cache:
  directories:
    - node_modules
   