language: node_js
node_js:
  - "6.9.4"
before_install:
  - git config --global push.default matching
  - git config --global user.name "sooglejay"
  - git config --global user.email "394055524@qq.com"
  - export TZ='Asia/Shanghai'  # 设置时区

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-sass --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save


script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Auto Builder From Travis"
  - git push --quiet --force https://$DEPLOY_REPO@github.com/sooglejay/sooglejay.github.io.git master

branches:
  only:
    - dev
cache:
  directories:
    - node_modules
